---
- name: Install all required dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-setuptools
    - python3-dev
    - build-essential
    - python3-pip

- name: Install MySQL database
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - mysql-client

- name: Start MySQL Service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Install MySQL module for Python via apt
  apt:
    name: python3-pymysql
    state: present
    update_cache: yes
  become: yes
